name: Push App Source Language

on:
  push:
    branches: ["main"]
    paths:
      - "src/*.rs"
      - "scripts/extract_locale_strings.py"
      - ".github/workflows/push-app-source-language.yml"

jobs:
  extract:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
      - uses: actions/checkout@v4
  
      - name: Set up Python
        uses: actions/setup-python@v5
  
      - name: Extract localizable strings
        run: python scripts/extract_locale_strings.py
  
      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "Update source language file"
          add: "locale/en.json"

  push:
    needs: extract
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4

    - name: Install transifex client
      run: |
        curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash

    - name: Push source language
      env:
        TX_TOKEN: ${{ secrets.TX_TOKEN }}
      run: |
        ./tx push --source
